services:
  - type: web
    name: employee-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn employee_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: lc_1yip6=u+*o9u*rz0z^ns310l*p7*pf@#9e&ozdryj_e3@sr
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: ems
          property: connectionString
databases:
  - name: ems
